Add data checksums

diff --git a/bin/postgresql-setup.in b/bin/postgresql-setup.in
--- a/bin/postgresql-setup.in
+++ b/bin/postgresql-setup.in
@@ -59,6 +59,16 @@ option_upgradefrom="@NAME_DEFAULT_PREV_SERVICE@"
 srvsuff=
 test 0 -eq @WANT_SYSVINIT@ && srvsuff=".service"
 
+if [ @PGMAJORVERSION@ -ge 18 ]; then
+    checksums_default_line="
+                             Default behavior when initializing (not upgrading).
+                             To upgrade to PostgreSQL @PGMAJORVERSION@ without
+                             enabling data checksums, add --no-data-checksums
+                             to PGSETUP_INITDB_OPTIONS (will override this flag)
+                             If data checksums are already enabled, there is no
+                             need to specify this flag."
+fi
+
 USAGE_STRING=$"\
 Usage: $0 MODE_OPTION [--unit=UNIT_NAME] [OPTION...]
 
@@ -97,6 +107,9 @@ Options:
   --upgrade-from=ID          Specify id \"old\" postgresql stack to upgrade
                              from.  List of available IDs can be listed by
                              --upgrade-ids.  Default is '$option_upgradefrom'.
+  --data-checksums           Enable data checksums for the data directory.
+                             If upgrading, they will be enabled before
+                             performing the upgrade.${checksums_default_line}
 
 Other options:
   --help                     show this help
@@ -213,8 +226,60 @@ old_data_in_use()
 }
 
 
+enable_checksums()
+{
+    local old_datadir="$1"
+    local old_bindir="$2"
+
+    if [ $option_data_checksums -eq 1 ] \
+    && ! echo "$PGSETUP_INITDB_OPTIONS" | grep -qE -- "--no-data-checksums"; then
+        debug "enabling data checksums"
+        local enable_checksums_result=$("$old_bindir/pg_checksums -e $old_datadir 2>&1")
+        local enable_checksums_code=$?
+        if [ ! $enable_checksums_code ]; then
+            error "Could not enable checksums!"
+            error_q $enable_checksums_result
+            return 1
+        fi
+        if [ @PGMAJORVERSION@ -lt 18 ]; then
+            if [ -n "$PGSETUP_INITDB_OPTIONS" ]; then
+                export PGSETUP_INITDB_OPTIONS="$PGSETUP_INITDB_OPTIONS --data-checksums"
+            else
+                export PGSETUP_INITDB_OPTIONS="--data-checksums"
+            fi
+        fi
+    elif [ $option_data_checksums -eq 1 ]; then
+        warn "Both --data-checksums and --no-data-checksums flags specified,"
+        warn_q "upgrading without enabling data checksums!"
+        option_data_checksums=0
+    fi
+}
+
+
 upgrade()
 {
+    info "Checking data checksums"
+    # timeout for large databases, if checksums are disabled, this command will fail fast
+    checksums_result=$("timeout 1 $upgradefrom_engine/pg_checksums $upgradefrom_data 2>&1")
+    checksums_code=$?
+    # if timed out, the exit code is 124
+    if [ $checksums_code -ne 0 ] && [ $checksums_code -ne 124 ]; then
+        if echo $checksums_result | grep -q "not enabled" \
+        && [ @PGMAJORVERSION@ -ge 18 ] && [ $option_data_checksums -ne 1 ] \
+        && ! echo "$PGSETUP_INITDB_OPTIONS" | grep -qE -- "--no-data-checksums"; then
+            error "PostgreSQL @PGMAJORVERSION@ has data checksums enabled by default,"
+            error_q "while your current data directory does not. Please either use the"
+            error_q "--data-checksums flag to enable them before upgrading, or add"
+            error_q "--no-data-checksums to the PGSETUP_INITDB_OPTIONS environment variable."
+            exit 1
+        else
+            # this means that checksums are enabled but something else failed
+            error "Checksum check failed! Output from pg_checksums:"
+            error_q $checksums_result
+            exit 1
+        fi
+    fi
+
     local inplace=false
     test "$pgdata" = "$upgradefrom_data" && inplace=true
 
@@ -275,6 +340,8 @@ upgrade()
 
     info $"Upgrading database."
 
+    enable_checksums "$pgdataold" "$upgradefrom_engine"
+
     scls_upgrade_hacks=
     test -n "$upgradefrom_scls" && {
         debug "scls [$upgradefrom_scls] will be enabled"
@@ -300,7 +367,7 @@ upgrade()
         # remove it after this unsuccessful upgrade.
         script_result=1
         failure_cleanup=false
-    elif perform_initdb; then
+    elif  perform_initdb; then
         $inplace && link_option=--link
 
         # After creating the empty new-format database, do the upgrade
@@ -642,7 +709,7 @@ long_opts="\
 initdb,upgrade,\
 new-systemd-unit,upgrade-ids,\
 unit:,service:,port:,datadir:,upgrade-from:,upgrade-from-unit:,\
-debug,\
+data-checksums,debug,\
 version,help,usage"
 
 args=`getopt -o "$short_opts" -l "$long_opts" -n "@NAME_BINARYBASE@-setup" -- "$@"` \
@@ -699,6 +766,11 @@ while true; do
         --upgrade-ids)
             parse_upgrade_setup help
             exit 0
+            ;;
+
+        --data-checksums)
+            option_data_checksums=1
+            shift
             ;;
 
         --version)
